databases:
    es_db:
        import_path: "ElasticSearchDB"
        config:
            host: "localhost"
            port: 9200
            login: ""
            password: ""
            replication: 1
    consul_db:
        import_path: "ConsulDB"
        config:
            host: "127.0.0.1"
            port: 8500
            login: ""
            password: ""
models:
-   import_path: "csm.core.blogic.models.alerts.AlertModel"
    database: "es_db"
    config:
        es_db:
            collection: "alerts"
-   import_path: "csm.core.blogic.models.alerts.AlertsHistoryModel"
    database: "es_db"
    config:
        es_db:
            collection: "alerts-history"
-   import_path: "csm.core.data.models.users.User"
    database: "consul_db"
    config:
        consul_db:
            collection: "user_collection"
-   import_path: "csm.core.data.models.system_config.SystemConfigSettings"
    database: "consul_db"
    config:
        consul_db:
            collection: "system_config"
-   import_path: "csm.core.data.models.usl.Volume"
    database: "consul_db"
    config:
        consul_db:
            collection: "usl_volume_collection"
-   import_path: "csm.core.data.models.onboarding.OnboardingConfig"
    database: "consul_db"
    config:
        consul_db:
            collection: "onboarding_config"
-   import_path: "csm.core.data.models.system_config.OnboardingLicense"
    database: "consul_db"
    config:
        consul_db:
            collection: "product_licenses"
-   import_path: "csm.core.blogic.models.support_bundle.SupportBundleModel"
    database: "es_db"
    config:
        es_db:
            collection: "supportbundle"
-   import_path: "csm.core.blogic.models.audit_log.CsmAuditLogModel"
    database: "es_db"
    config:
        es_db:
            collection: "csmauditlog"

-   import_path: "csm.core.blogic.models.audit_log.S3AuditLogModel"
    database: "es_db"
    config:
        es_db:
            collection: "s3-rsys-index"
-   import_path: "csm.core.data.models.upgrade.UpdateStatusEntry"
    database: "consul_db"
    config:
        consul_db:
            collection: "update_status_entries"
-   import_path: "eos.utils.security.secure_storage.NamedEncryptedBytes"
    database: "consul_db"
    config:
        consul_db:
            collection: "secure_storage"
