{
 "title": "Seagate EOS",
 "description": "Dashboard for Seagate EOS",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Capacity (bytes)",
   "type": "grafana-piechart-panel",
   "description": "Capacity of mero",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "target": "alias(cluster.gauges.mero.free_space, 'Free Space')"
    },
    {
     "target": "alias(cluster.gauges.mero.used_space, 'Used Space')"
    }
   ]
  },
  {
   "title": "Throughput (bytes/s)",
   "type": "graph",
   "description": "Throughput of the cluster",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes trasferred per second" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(#A, #B), 'Total')",
     "targetFull": "alias(sumSeries(alias(movingAverage(perSecond(cluster.gauges.haproxy.app-main.BACKEND.bin), '2min'), 'Write'), alias(movingAverage(perSecond(cluster.gauges.haproxy.app-main.BACKEND.bout), '2min'), 'Read')), 'Total')"
    },
    {
     "refCount": -1,
     "target": "alias(movingAverage(perSecond(cluster.gauges.haproxy.app-main.BACKEND.bout), '2min'), 'Read')"
    },
    {
     "refCount": 1,
     "target": "alias(movingAverage(perSecond(cluster.gauges.haproxy.app-main.BACKEND.bin), '2min'), 'Write')"
    }
   ]
  },
  {
   "title": "IO (Ops/s)",
   "type": "graph",
   "description": "Object IOPS of the cluster",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ops", "label": "Ops per second" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(#B, #A), 'Total')",
     "targetFull": "alias(sumSeries(alias(sumSeries(cluster.counters.get_object_request_count.rate, cluster.counters.get_multipart_parts_request_count.rate), 'Read'), alias(sumSeries(cluster.counters.put_object_request_count.rate, cluster.counters.put_multipart_part_request_count.rate), 'Write')), 'Total')"
    },
    {
     "refCount": -1,
     "target": "alias(sumSeries(cluster.counters.get_object_request_count.rate, cluster.counters.get_multipart_parts_request_count.rate), 'Read')"
    },
    {
     "refCount": 1,
     "target": "alias(sumSeries(cluster.counters.put_object_request_count.rate, cluster.counters.put_multipart_part_request_count.rate), 'Write')"
    }
   ]
  },
  {
   "title": "Latency (Object operations) (ms)",
   "type": "graph",
   "description": "Cluster latency for different operations",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    {
     "format": "ms",
     "label": "Average lantency (in millisecond)"
    }
   ],
   "targets": [
    {
     "target": "alias(averageSeries(cluster.timers.create_object_success.mean, cluster.timers.multipart_create_object_success.mean, cluster.timers.chunkupload_create_object_success.mean), 'Create')"
    },
    {
     "target": "alias(cluster.timers.read_object_data_success.mean, 'Read')"
    },
    {
     "target": "alias(averageSeries(cluster.timers.delete_objects_from_clovis_success.mean, cluster.timers.delete_object_from_clovis_success.mean), 'Delete')"
    },
    {
     "target": "alias(cluster.timers.write_to_clovis_op_success.mean, 'Write')"
    },
    {
     "target": "alias(cluster.timers.get_keyval_success.mean, 'ReadKV')"
    },
    {
     "target": "alias(cluster.timers.put_keyval_success.mean, 'WriteKV')"
    },
    {
     "target": "alias(cluster.timers.delete_keyval_success.mean, 'DeleteKV')"
    }
   ]
  },
  {
   "title": "Metadata (Ops/s)",
   "type": "graph",
   "description": "Metadata operation per second.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "ops", "label": "Ops per second" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "alias(sumSeries(cluster.counters.delete_object_request_count.rate, cluster.counters.delete_multiobject_request_count.rate), 'Delete')"
    },
    {
     "target": "alias(sumSeries(#A, #G, #H, #I, #J, #L, #M, #N, #O, #P), 'Total')",
     "targetFull": "alias(sumSeries(alias(sumSeries(cluster.counters.delete_object_request_count.rate, cluster.counters.delete_multiobject_request_count.rate), 'Delete'), alias(cluster.counters.get_object_acl_request_count.rate, 'ACL Get'), alias(cluster.counters.put_object_acl_request_count.rate, 'ACL Put'), alias(cluster.counters.post_multipart_complete_request_count.rate, 'Multipart Complete'), alias(cluster.counters.post_multipart_initiate_request_count.rate, 'Multipart Initiate'), alias(cluster.counters.abort_multipart_request_count.rate, 'Multipart Abort'), alias(cluster.counters.head_object_request_count.rate, 'Head'), alias(cluster.counters.put_object_chunkupload_request_count.rate, 'Chunkupload Put'), alias(cluster.counters.unsupported_api_count.rate, 'Unsupported API'), alias(cluster.counters.get_service_request_count.rate, 'Get Service')), 'Total')"
    },
    {
     "refCount": 1,
     "target": "alias(cluster.counters.get_object_acl_request_count.rate, 'ACL Get')"
    },
    {
     "refCount": 1,
     "target": "alias(cluster.counters.put_object_acl_request_count.rate, 'ACL Put')"
    },
    {
     "refCount": 1,
     "target": "alias(cluster.counters.post_multipart_complete_request_count.rate, 'Multipart Complete')"
    },
    {
     "refCount": 1,
     "target": "alias(cluster.counters.post_multipart_initiate_request_count.rate, 'Multipart Initiate')"
    },
    {
     "refCount": 1,
     "target": "alias(cluster.counters.abort_multipart_request_count.rate, 'Multipart Abort')"
    },
    {
     "refCount": 1,
     "target": "alias(cluster.counters.head_object_request_count.rate, 'Head')"
    },
    {
     "refCount": 1,
     "target": "alias(cluster.counters.put_object_chunkupload_request_count.rate, 'Chunkupload Put')"
    },
    {
     "refCount": 1,
     "target": "alias(cluster.counters.unsupported_api_count.rate, 'Unsupported API')"
    },
    {
     "refCount": 1,
     "target": "alias(cluster.counters.get_service_request_count.rate, 'Get Service')"
    }
   ]
  },
  {
   "title": "S3 Server Error (count)",
   "type": "graph",
   "description": "S3server Error",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "locale", "label": "Error count" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(cluster.timers.create_object_failed.count, cluster.timers.multipart_create_object_failed.count, cluster.timers.chunkupload_create_object_failed.count), 'Create Object')"
    },
    {
     "target": "alias(sumSeries(cluster.timers.delete_object_from_clovis_failed.count, cluster.timers.delete_objects_from_clovis_failed.count), 'Delete Object')"
    },
    {
     "target": "alias(cluster.timers.read_object_data_failed.count, 'Get Object')"
    },
    {
     "target": "alias(cluster.timers.write_to_clovis_op_failed.count, 'Put Object')"
    },
    {
     "target": "alias(cluster.timers.create_index_op_failed.count, 'Create Index')"
    },
    {
     "target": "alias(cluster.timers.delete_index_op_failed.count, 'Delete Index')"
    },
    {
     "target": "alias(cluster.timers.get_keyval_failed.count, 'Get Keyval')"
    },
    {
     "target": "alias(cluster.timers.put_keyval_failed.count, 'Put Keyval')"
    },
    {
     "target": "alias(cluster.timers.delete_keyval_failed.count, 'Delete Keyval')"
    },
    {
     "target": "alias(cluster.counters.internal_error_count.count, 'Internal Error')"
    }
   ]
  },
  {
   "title": "Haproxy Error (count)",
   "type": "graph",
   "description": "Haproxy Error",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "locale", "label": "Error count" }
   ],
   "targets": [
    {
     "target": "alias(derivative(cluster.gauges.haproxy.app-main.BACKEND.hrsp_4xx), 'HTTP Client')"
    },
    {
     "target": "alias(derivative(cluster.gauges.haproxy.app-main.BACKEND.hrsp_5xx), 'HTTP Server')"
    },
    {
     "target": "alias(derivative(cluster.gauges.haproxy.app-main.BACKEND.econ), 'Connection')"
    }
   ]
  },
  {
   "title": "Auth Server Error (count)",
   "type": "graph",
   "description": "Auth Server Error",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "locale", "label": "Error count" }
   ],
   "targets": [
    {
     "target": "alias(cluster.counters.authentication_failed_invalid_accesskey_count.count, 'Invalid Access Key')"
    },
    {
     "target": "alias(cluster.counters.authentication_failed_signature_mismatch_count.count, 'Signature Mismatch')"
    }
   ]
  }
 ]
}